(async()=>{
 const q=new URLSearchParams(location.search),league=(q.get("league")||"epl").toLowerCase(),root=document.getElementById("accuracy");
 const n=(v,d=2)=>v==null?"—":Number(v).toFixed(d),p=v=>v==null?"—":`${(100*Number(v)).toFixed(1)}%`,esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
 try{
  const r=await fetch(`data/${league}.json?ts=${Date.now()}`,{cache:"no-store"}),d=await r.json(),a=d.accuracy?.total_goals||{},teams=Object.fromEntries((d.teams||[]).map(t=>[t.slug,t.name]));
  const upcoming=(d.fixtures||[]).filter(f=>!["final","postponed","cancelled","abandoned"].includes(String(f.status||"").toLowerCase())&&f.expected_total_goals!=null).slice(0,12);
  root.innerHTML=`<header><div><div class="muted">${esc(d.meta?.name||league.toUpperCase())} · ${esc(d.meta?.season||"")}</div><h1>Forecast Accuracy</h1><div class="muted">Frozen pre-match auditing with total-goals calibration.</div></div><nav><a class="${league==="epl"?"active":""}" href="?league=epl">Premier League</a><a class="${league==="mls"?"active":""}" href="?league=mls">MLS</a></nav></header>
  <section class="kpis"><div><span>Matches audited</span><strong>${a.matches||0}</strong></div><div><span>Total-goals MAE</span><strong>${n(a.mae,3)}</strong></div><div><span>RMSE</span><strong>${n(a.rmse,3)}</strong></div><div><span>Bias</span><strong>${n(a.bias_predicted_minus_actual,3)}</strong></div><div><span>Within ±0.5</span><strong>${p(a.within_0_5)}</strong></div><div><span>Within ±1.0</span><strong>${p(a.within_1_0)}</strong></div></section>
  <section class="panel"><h2>Upcoming expected total goals</h2><div class="fixtures">${upcoming.map(f=>`<div class="fixture"><b>${esc(teams[f.home]||f.home)} vs ${esc(teams[f.away]||f.away)}</b><div class="goal"><span>Expected total goals</span><b>${n(f.expected_total_goals)}</b></div></div>`).join("")||'<div class="muted">No upcoming modeled fixtures.</div>'}</div></section>
  <section class="panel"><h2>Calibration by predicted total</h2><div class="scroll"><table><thead><tr><th>Range</th><th>Matches</th><th>Predicted avg</th><th>Actual avg</th><th>Bias</th></tr></thead><tbody>${(a.calibration_bins||[]).map(x=>`<tr><td>${x.range}</td><td>${x.matches}</td><td>${n(x.mean_predicted,3)}</td><td>${n(x.mean_actual,3)}</td><td>${n(x.bias_predicted_minus_actual,3)}</td></tr>`).join("")}</tbody></table></div></section>
  <section class="panel"><h2>Frozen forecast audit</h2><div class="scroll"><table><thead><tr><th>Match</th><th>Predicted total</th><th>Actual</th><th>Abs. error</th></tr></thead><tbody>${[...(d.accuracy_history||[])].reverse().slice(0,100).map(x=>`<tr><td>${esc(teams[x.home]||x.home)} vs ${esc(teams[x.away]||x.away)}</td><td>${n(x.predicted_total)}</td><td>${n(x.actual_total,0)}</td><td>${n(x.absolute_error)}</td></tr>`).join("")}</tbody></table></div></section>`;
 }catch(e){root.innerHTML=`<p>Could not load accuracy data: ${esc(e.message)}</p>`}
})();
